### PR TITLE
Added local LLM support

### LINKED ISSUE #3: Feature Request: Local LLM Support (like Ollama, Llama.cpp, Oobabooga)
Is there any news for local LLM support?

I've successfully Initialized OpenAI with local LLM for a different use case:
client = OpenAI(base_url="http://127.0.0.1:11434", api_key="ollama")
client = OpenAI(base_url="http://localhost:1234/v1", api_key="lm-studio")

### PR DESCRIPTION
**Pull request by JustAnotherIdea**
Adds local LLM support

Could also now use other hosted LLMs by specifying their url.

Results from local LLM are highly dependent on the model and settings used.

Resolves #3

### CODE REVIEW

**Comment by Daxiongmao87** [comment]
Hey @JustAnotherIdea , thank you for contributing.  Just want to make sure that the original non-local LLM functionality has been tested to ensure its original functions are preserved.  

Are you able to verify or do you need me to test?

**Comment by JustAnotherIdea** [comment]
I'm like %99 sure I tested it. I'll double check tonight

**Comment by JustAnotherIdea** [comment]
Apologies for the delay. It is confirmed still working.

**Comment by Daxiongmao87** [comment]
@JustAnotherIdea no need to apologize, we're all doing this on our spare time lol.  I appreciate your contribution dearly.  I'll go ahead and update the manifest version number sometime this week and merge the changes.  I think the version bump is all that's left.

**Comment by Daxiongmao87** [comment]
Actually @JustAnotherIdea I may have gotten the standard process wrong.  I don't think I can easily make changes to your repo/branch.  Would you be willing to increment the version number here?

https://github.com/Daxiongmao87/legend-lore-foundry/blob/dde389cdc35108c03a60c2ea1315173dfdc8fded/module.json#L4

With that change I'll approve and merge

**Comment by JustAnotherIdea** [comment]
Done

**Comment by JustAnotherIdea** [comment]
Looking at the workflow you have in release.yaml I _think_ all you need to do is create a new release with the tag v0.3.2-release, select main as the branch, and publish the release. That should trigger the workflow. I'm not sure how the release is updated on the foundry site though. I haven't released my own module yet.

**Comment by Daxiongmao87** [comment]
Hey @JustAnotherIdea , just realized, what API did you write this for? ollama, text-generation-webui, openai-compatible api, etc? We probably should update the readme to include any extra guidance.

**Comment by JustAnotherIdea** [comment]
Any OpenAI compatible API should work. I tested using LM studio. Adding some info on this would be beneficial. I will put together my findings when I have the time and add them (maybe as a link to another document so it can get updated with new findings without a PR)

**Comment by Daxiongmao87** [comment]
> Looking at the workflow you have in release.yaml I _think_ all you need to do is create a new release with the tag v0.3.2-release, select main as the branch, and publish the release. That should trigger the workflow. I'm not sure how the release is updated on the foundry site though. I haven't released my own module yet.

Hey @JustAnotherIdea i went ahead and finally got around to updating the release.  It's now actually 0.4.0 (honestly should probably be 1.0, otherwise I wouldn't know what would be considered a 1.0 at this point since it is a functioning service reaching MVP), since I consider the local LLM support to be a new feature, it probably deserves the minor version bump as opposed to a patch.

**Pull request merged**
